export const PHET_MESSAGE_TYPES = {
  READY: 'AIWEB_READY',
  PLAY: 'AIWEB_PLAY',
  PAUSE: 'AIWEB_PAUSE',
  STEP_BACKWARD: 'AIWEB_STEP_BACKWARD',
  STEP_FORWARD: 'AIWEB_STEP_FORWARD',
  RESET: 'AIWEB_RESET',
  STIMULATE: 'AIWEB_STIMULATE',
  SPEED: 'AIWEB_SPEED',
  SET_ALL_IONS: 'AIWEB_SET_ALL_IONS',
  SET_CHARGES: 'AIWEB_SET_CHARGES',
  SET_CONCENTRATIONS: 'AIWEB_SET_CONCENTRATIONS',
  SET_POTENTIAL_CHART: 'AIWEB_SET_POTENTIAL_CHART',
  SPIKE_STARTED: 'AIWEB_SPIKE_STARTED',
  SPIKE_FINISHED: 'AIWEB_SPIKE_FINISHED',
  STATE: 'AIWEB_RUNTIME_STATE',
}

export const PHET_SPEED_VALUES = {
  SLOW: 'slow',
  NORMAL: 'normal',
  FAST: 'fast',
}

export function isPhetMessageType(type) {
  return Object.values(PHET_MESSAGE_TYPES).includes(type)
}
